// Generated by QuickJSKit. Do not edit.

declare namespace QuickJSKit {
    /**
     * A user visible to embedded scripts.
     *
     * @remarks
     * Values are immutable snapshots of host data.
     */
    interface User {
        /** The stable user identifier. */
        readonly id: number;

        /**
         * The display name.
         *
         * @defaultValue "Anonymous"
         */
        readonly name: string;
    }
}

interface HostConfiguration {
    readonly environment: string;
}

declare namespace Example.Models {
    interface Session {
        readonly token: string;
    }
}

/**
 * Loads a user.
 *
 * @param id - Stable user identifier.
 * @returns The matching {@link QuickJSKit.User}, or `null`.
 *
 * @throws {@link SwiftError}
 * The host database operation failed.
 *
 * @example Load a user
 * ```ts
 * const user = await loadUser(42n);
 * ```
 *
 * @see {@link QuickJSKit.User}
 * @deprecated Use {@link fetchUser} instead.
 */
declare function loadUser(id: number | bigint): Promise<QuickJSKit.User | null>;

declare module "host:answer" {
    /** Metadata exported by the host module. */
    export interface AnswerMetadata {
        readonly source: string;
    }

    export const answer: number;
    export const metadata: AnswerMetadata;
}
