// Generated by QuickJSKit. Do not edit.

declare namespace QuickJSKit {
    interface User {
        readonly id: number;
        readonly name: string;
    }
}

declare function loadUser(id: number | bigint): Promise<QuickJSKit.User>;

declare module "host:answer" {
    export const answer: number;
}
