import Foundation
import QuickJSKit
import Testing

@Suite("TypeScript tooling examples")
struct TypeScriptToolingExamplesTests {
    struct User: Codable, Sendable, Equatable, TypeScriptSchemaProviding {
        let id: Int
        let name: String

        static let typeScriptSchema = TypeScriptSchema.interface(
            "User",
            documentation: "A user visible to embedded scripts.",
            properties: [
                .init("id", type: .number, isReadonly: true),
                .init("name", type: .string, isReadonly: true),
            ]
        )
    }

    struct ModuleUser: Codable, Sendable, TypeScriptSchemaProviding {
        let id: Int

        static let typeScriptSchema = TypeScriptSchema.interface(
            "User",
            scope: .module("host:users"),
            documentation: "A user exported by the host users module.",
            properties: [
                .init("id", type: .number, isReadonly: true),
            ]
        )
    }

    @Test("a runtime snapshot renders typed globals deterministically")
    func snapshotRendersTypedGlobals() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "loadUser",
            options: .init(
                parameterNames: ["id", "nickname"],
                documentation: "Loads a user."
            )
        ) { (_: Int64, _: String?) async throws -> User? in
            User(id: 42, name: "Ada")
        }

        let environment = try await runtime.environmentDescription()
        let declarations = try environment.typeScriptDeclarations()

        #expect(declarations == """
        // Generated by QuickJSKit. Do not edit.

        declare namespace QuickJSKit {
            /** A user visible to embedded scripts. */
            interface User {
                readonly id: number;
                readonly name: string;
            }
        }

        /**
         * Loads a user.
         *
         * @throws When the Swift operation fails.
         */
        declare function loadUser(id: number | bigint, nickname?: string | null): Promise<QuickJSKit.User | null>;
        """ + "\n")
    }

    @Test("schemas can use global named and module declaration scopes")
    func schemasUseExplicitDeclarationScopes() async throws {
        let global = TypeScriptSchema.interface(
            "Configuration",
            scope: .global,
            properties: [.init("debug", type: .boolean)]
        )
        let model = TypeScriptSchema.interface(
            "User",
            scope: "Acme.Models",
            properties: [.init("id", type: .number)]
        )
        let service = TypeScriptSchema.alias(
            "UserResult",
            to: .named("User", scope: "Acme.Models"),
            scope: "Acme.Services"
        )

        let runtime = try JavaScriptRuntime()
        try await runtime.defineModule("host:users") { module in
            module.function("loadUser") { () -> ModuleUser in ModuleUser(id: 42) }
        }
        try await runtime.function("cachedUser") { () -> ModuleUser in ModuleUser(id: 42) }

        let declarations = try await runtime.environmentDescription(
            including: [global, model, service]
        ).typeScriptDeclarations()

        #expect(declarations.contains("interface Configuration"))
        #expect(declarations.contains("declare namespace Acme.Models"))
        #expect(declarations.contains("declare namespace Acme.Services"))
        #expect(declarations.contains("type UserResult = Acme.Models.User;"))
        #expect(declarations.contains("declare function cachedUser(): import(\"host:users\").User;"))
        #expect(declarations.contains("export interface User"))
        #expect(declarations.contains("export function loadUser(): User;"))
    }

    @Test("the default type scope is customizable without changing schemas")
    func defaultTypeScopeIsCustomizable() async throws {
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription(including: [User.typeScriptSchema])

        let namespaced = try environment.typeScriptDeclarations(
            options: .init(defaultTypeScope: "Example.Models")
        )
        let global = try environment.typeScriptDeclarations(
            options: .init(defaultTypeScope: .global)
        )

        #expect(namespaced.contains("declare namespace Example.Models"))
        #expect(!global.contains("declare namespace"))
        #expect(global.contains("interface User"))
    }

    @Test("equal names are independent across declaration scopes")
    func equalNamesAreIndependentAcrossScopes() async throws {
        let first = TypeScriptSchema.interface(
            "Result",
            scope: "First",
            properties: [.init("value", type: .string)]
        )
        let second = TypeScriptSchema.interface(
            "Result",
            scope: "Second",
            properties: [.init("value", type: .number)]
        )
        let runtime = try JavaScriptRuntime()
        let declarations = try await runtime.environmentDescription(including: [second, first])
            .typeScriptDeclarations()

        #expect(declarations.contains("declare namespace First"))
        #expect(declarations.contains("declare namespace Second"))
        let firstIndex = try #require(
            declarations.firstRange(of: "declare namespace First")?.lowerBound
        )
        let secondIndex = try #require(
            declarations.firstRange(of: "declare namespace Second")?.lowerBound
        )
        #expect(firstIndex < secondIndex)
    }

    @Test("inherited and explicit equivalent scopes deduplicate definitions")
    func equivalentScopesDeduplicateDefinitions() async throws {
        let inherited = TypeScriptSchema(
            type: .named("Value"),
            definitions: [.alias(name: "Value", type: .string)],
            scope: "Models"
        )
        let explicit = TypeScriptSchema(
            type: .named("Value", scope: "Models"),
            definitions: [
                .alias(name: "Value", scope: "Models", type: .string),
            ],
            scope: .global
        )
        let runtime = try JavaScriptRuntime()
        let declarations = try await runtime.environmentDescription(
            including: [explicit, inherited]
        ).typeScriptDeclarations()

        #expect(declarations.components(separatedBy: "type Value = string;").count == 2)
    }

    @Test("source modules combine generated schemas with companion declarations")
    func sourceModulesCombineSchemasAndCompanions() async throws {
        let schema = TypeScriptSchema.interface(
            "Metadata",
            scope: .module("host:answer"),
            properties: [.init("source", type: .string)]
        )
        let runtime = try JavaScriptRuntime()
        try await runtime.registerModule(
            "export const answer = 42;",
            as: "host:answer",
            typeScriptDeclarations: .init("export const answer: number;")
        )

        let declarations = try await runtime.environmentDescription(including: [schema])
            .typeScriptDeclarations()

        #expect(declarations.contains("export interface Metadata"))
        #expect(declarations.contains("export const answer: number;"))
        let schemaIndex = try #require(
            declarations.firstRange(of: "export interface Metadata")?.lowerBound
        )
        let companionIndex = try #require(
            declarations.firstRange(of: "export const answer")?.lowerBound
        )
        #expect(schemaIndex < companionIndex)
    }

    @Test("structured TSDoc describes complete function behavior to IDEs")
    func structuredTSDocDescribesFunctions() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "loadUser",
            options: .init(
                parameterNames: ["id"],
                documentation: .init(
                    summary: "Loads a user.",
                    remarks: "Uses the host database and returns `null` when no user exists.",
                    parameters: ["id": "Stable user identifier."],
                    returns: "The matching {@link QuickJSKit.User}, or `null`.",
                    errors: [
                        .init(
                            reference: "SwiftError",
                            description: "The database operation failed."
                        ),
                        .init(description: "The request was cancelled."),
                    ],
                    examples: [
                        .init(
                            title: "Load one user",
                            body: """
                            ```ts
                            const user = await loadUser(42);
                            ```
                            """
                        ),
                    ],
                    seeAlso: ["{@link QuickJSKit.User}"],
                    deprecated: "Use {@link fetchUser} instead."
                )
            )
        ) { (_: Int64) async throws -> User? in
            User(id: 42, name: "Ada")
        }

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()

        #expect(declarations.contains("""
        /**
         * Loads a user.
         *
         * @remarks
         * Uses the host database and returns `null` when no user exists.
         *
         * @param id - Stable user identifier.
         *
         * @returns The matching {@link QuickJSKit.User}, or `null`.
         *
         * @throws {@link SwiftError}
         * The database operation failed.
         *
         * @throws
         * The request was cancelled.
         *
         * @example Load one user
         * ```ts
         * const user = await loadUser(42);
         * ```
         *
         * @see {@link QuickJSKit.User}
         *
         * @deprecated Use {@link fetchUser} instead.
         */
        declare function loadUser(id: number | bigint): Promise<QuickJSKit.User | null>;
        """))
    }

    @Test("schemas render rich documentation defaults and enum case guidance")
    func schemasRenderRichDocumentation() async throws {
        let schema = TypeScriptSchema(
            type: .named("Preferences"),
            definitions: [
                .interface(
                    name: "Preferences",
                    documentation: .init(
                        summary: "User-visible preferences.",
                        remarks: "Values are immutable snapshots."
                    ),
                    properties: [
                        .init(
                            "theme",
                            type: .named("Theme"),
                            isReadonly: true,
                            documentation: "The selected color theme.",
                            defaultValue: #""system""#
                        ),
                    ]
                ),
                .enumeration(
                    name: "Theme",
                    documentation: "A supported color theme.",
                    cases: [
                        .init(
                            "system",
                            value: .string("system"),
                            documentation: "Follows the operating system."
                        ),
                        .init(
                            "dark",
                            value: .string("dark"),
                            documentation: "Always uses dark colors."
                        ),
                    ]
                ),
            ]
        )
        let runtime = try JavaScriptRuntime()
        let declarations = try await runtime.environmentDescription(including: [schema])
            .typeScriptDeclarations()

        #expect(declarations.contains("@remarks\n     * Values are immutable snapshots."))
        #expect(declarations.contains("@defaultValue \"system\""))
        #expect(declarations.contains("`system` (`\"system\"`): Follows the operating system."))
        #expect(declarations.contains("`dark` (`\"dark\"`): Always uses dark colors."))
    }

    @Test("objects globals and modules expose container documentation")
    func containersExposeDocumentation() async throws {
        final class Store: Sendable {}

        let runtime = try JavaScriptRuntime()
        try await runtime.global.set(
            "1.0",
            forProperty: "version",
            documentation: "The host API version."
        )
        try await runtime.export(
            Store(),
            as: "store",
            documentation: "Persistent application storage."
        ) { _, export in
            export.value(
                true,
                as: "available",
                documentation: "Whether storage is available."
            )
        }
        try await runtime.defineModule(
            "host:settings",
            documentation: "Host-provided settings."
        ) { module in
            module.value("dark", as: "theme", documentation: "The active theme.")
        }
        try await runtime.registerModule(
            "export const platform = 'swift';",
            as: "host:platform",
            documentation: "Platform information.",
            typeScriptDeclarations: .init("export const platform: string;")
        )

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains("/** The host API version. */\ndeclare let version"))
        #expect(declarations.contains("/** Persistent application storage. */\ndeclare const store"))
        #expect(declarations.contains("/** Host-provided settings. */\ndeclare module \"host:settings\""))
        #expect(declarations.contains("/** Platform information. */\ndeclare module \"host:platform\""))
    }

    @Test("complete documentation mode reports missing fields precisely")
    func completeDocumentationReportsMissingFields() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "lookup",
            options: .init(
                parameterNames: ["id"],
                documentation: .init(summary: "Looks up a value.")
            )
        ) { (_: Int) throws -> String in "value" }
        let environment = try await runtime.environmentDescription()

        do {
            _ = try environment.typeScriptDeclarations(
                options: .init(documentationCompleteness: .requireComplete)
            )
            Issue.record("Generation unexpectedly accepted incomplete documentation.")
        } catch let error as TypeScriptToolingError {
            #expect(error.message.contains("parameter 'id'"))
            #expect(error.message.contains("function 'lookup'"))
        }

        let permissive = try environment.typeScriptDeclarations()
        #expect(permissive.contains("@throws When the Swift operation fails."))
    }

    @Test("complete documentation mode accepts a fully documented environment")
    func completeDocumentationAcceptsCompleteEnvironment() async throws {
        let schema = TypeScriptSchema.interface(
            "Result",
            documentation: "A lookup result.",
            properties: [
                .init("value", type: .string, documentation: "The stored value."),
            ]
        )
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "lookup",
            options: .init(
                parameterNames: ["id"],
                documentation: .init(
                    summary: "Looks up a value.",
                    parameters: ["id": "Stable lookup identifier."],
                    returns: "The stored value.",
                    errors: [.init(description: "The lookup failed.")]
                )
            )
        ) { (_: Int) throws -> String in "value" }

        let declarations = try await runtime.environmentDescription(including: [schema])
            .typeScriptDeclarations(
                options: .init(documentationCompleteness: .requireComplete)
            )
        #expect(declarations.contains("declare function lookup"))
        #expect(declarations.contains("interface Result"))
    }

    @Test("complete documentation validates every generated symbol category")
    func completeDocumentationValidatesEverySymbolCategory() async throws {
        func strictFailure(
            _ environment: JavaScriptEnvironmentDescription
        ) -> String {
            let result = Result {
                try environment.typeScriptDeclarations(
                    options: .init(documentationCompleteness: .requireComplete)
                )
            }
            switch result {
            case .success:
                Issue.record("Generation unexpectedly accepted incomplete TSDoc.")
                return ""
            case let .failure(error):
                guard let toolingError = error as? TypeScriptToolingError else {
                    Issue.record("Generation produced the wrong error type: \(error)")
                    return ""
                }
                return toolingError.message
            }
        }

        let returnRuntime = try JavaScriptRuntime()
        try await returnRuntime.function(
            "value",
            options: .init(documentation: "Returns a value.")
        ) { () -> String in "value" }
        #expect(strictFailure(try await returnRuntime.environmentDescription()).contains(
            "return value"
        ))

        let errorRuntime = try JavaScriptRuntime()
        try await errorRuntime.function(
            "value",
            options: .init(
                documentation: .init(
                    summary: "Returns a value.",
                    returns: "The value."
                )
            )
        ) { () throws -> String in "value" }
        #expect(strictFailure(try await errorRuntime.environmentDescription()).contains(
            "thrown error"
        ))

        let globalRuntime = try JavaScriptRuntime()
        try await globalRuntime.global.set("value", forProperty: "value")
        #expect(strictFailure(try await globalRuntime.environmentDescription()).contains(
            "global value 'value'"
        ))

        final class Root: Sendable {}
        let objectRuntime = try JavaScriptRuntime()
        try await objectRuntime.export(Root(), as: "root") { _, export in
            export.value("value", as: "value", documentation: "The value.")
        }
        #expect(strictFailure(try await objectRuntime.environmentDescription()).contains(
            "exported object 'root'"
        ))

        let moduleRuntime = try JavaScriptRuntime()
        try await moduleRuntime.defineModule("host:values") { module in
            module.value("value", as: "value", documentation: "The value.")
        }
        #expect(strictFailure(try await moduleRuntime.environmentDescription()).contains(
            "Swift module 'host:values'"
        ))

        let sourceRuntime = try JavaScriptRuntime()
        try await sourceRuntime.registerModule(
            "export const value = 'value';",
            as: "host:source",
            typeScriptDeclarations: .init("export const value: string;")
        )
        #expect(strictFailure(try await sourceRuntime.environmentDescription()).contains(
            "source module 'host:source'"
        ))

        let definitionRuntime = try JavaScriptRuntime()
        let undocumentedDefinition = TypeScriptSchema.interface(
            "Undocumented",
            properties: [.init("value", type: .string, documentation: "The value.")]
        )
        #expect(strictFailure(
            try await definitionRuntime.environmentDescription(
                including: [undocumentedDefinition]
            )
        ).contains("TypeScript definition 'Undocumented'"))

        let undocumentedProperty = TypeScriptSchema.interface(
            "Container",
            documentation: "A documented container.",
            properties: [.init("value", type: .string)]
        )
        #expect(strictFailure(
            try await definitionRuntime.environmentDescription(
                including: [undocumentedProperty]
            )
        ).contains("TypeScript property 'Container.value'"))

        let undocumentedCase = TypeScriptSchema.enumeration(
            "State",
            documentation: "A documented state.",
            cases: [.init("ready", value: .string("ready"))]
        )
        #expect(strictFailure(
            try await definitionRuntime.environmentDescription(
                including: [undocumentedCase]
            )
        ).contains("TypeScript enum case 'State.ready'"))
    }

    @Test("TSDoc text is normalized and cannot inject block tags")
    func tsdocTextIsSafe() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.global.set(
            "value",
            forProperty: "safe",
            documentation: .init(
                summary: """

                Safe summary.
                @deprecated Injected tag. */

                """,
                seeAlso: ["{@link QuickJSKit.User}"]
            )
        )

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains("Safe summary."))
        #expect(declarations.contains("&#64;deprecated Injected tag. *\\/"))
        #expect(declarations.contains("@see {@link QuickJSKit.User}"))
        #expect(!declarations.contains("\n * @deprecated Injected tag"))
    }

    @Test("replacement and stale removal preserve the current documentation owner")
    func replacementPreservesCurrentDocumentation() async throws {
        let runtime = try JavaScriptRuntime()
        let stale = try await runtime.function(
            "value",
            options: .init(documentation: "Old function documentation.")
        ) { () -> String in "old" }
        try await runtime.global.set(
            "new",
            forProperty: "value",
            documentation: "Current value documentation."
        )
        _ = try await stale.remove()

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains("Current value documentation."))
        #expect(!declarations.contains("Old function documentation."))
    }

    @Test("workspace declarations preserve the exact structured TSDoc snapshot")
    func workspacePreservesStructuredTSDoc() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "answer",
            options: .init(
                documentation: .init(
                    summary: "Returns the answer.",
                    returns: "The answer."
                )
            )
        ) { () -> Int in 42 }
        let environment = try await runtime.environmentDescription()
        let options = TypeScriptDeclarationOptions(
            documentationCompleteness: .requireComplete
        )
        let declarations = try environment.typeScriptDeclarationBundle(
            options: options
        ).declarations
        let workspace = try environment.typeScriptWorkspace(
            options: .init(declarationOptions: options)
        )

        #expect(workspace.files.first {
            $0.path == "quickjskit.generated.d.ts"
        }?.contents == declarations)
    }

    @Test("invalid parameter documentation fails transactionally")
    func invalidParameterDocumentationFailsTransactionally() async throws {
        let runtime = try JavaScriptRuntime()

        await #expect(throws: JavaScriptError.self) {
            try await runtime.function(
                "lookup",
                options: .init(
                    parameterNames: ["id"],
                    documentation: .init(
                        summary: "Looks up a value.",
                        parameters: ["identifier": "An unknown parameter."]
                    )
                )
            ) { (_: Int) -> String in "value" }
        }
        let type: String = try await runtime.evaluate("typeof lookup")
        #expect(type == "undefined")

        await #expect(throws: JavaScriptError.self) {
            try await runtime.function(
                "unsafeError",
                options: .init(
                    documentation: .init(
                        summary: "Throws an error.",
                        errors: [
                            .init(
                                reference: "Error}",
                                description: "An unsafe link target."
                            ),
                        ]
                    )
                )
            ) { () throws -> Void in }
        }
        let unsafeType: String = try await runtime.evaluate("typeof unsafeError")
        #expect(unsafeType == "undefined")
    }

    @Test("loader-provided module documentation joins later snapshots")
    func loaderDocumentationJoinsSnapshots() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.setModuleLoader(
            JavaScriptModuleLoader { request in
                JavaScriptModuleSource(
                    source: "export const value = 42;",
                    sourceURL: "memory:///\(request.specifier).js",
                    documentation: "A lazily loaded module.",
                    typeScriptDeclarations: .init("export const value: number;")
                )
            }
        )
        try await runtime.preloadModule("lazy")

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains(
            "/** A lazily loaded module. */\ndeclare module \"lazy\""
        ))
    }

    @Test("invalid source module documentation rolls back registration")
    func invalidSourceDocumentationRollsBack() async throws {
        let runtime = try JavaScriptRuntime()
        await #expect(throws: JavaScriptError.self) {
            try await runtime.registerModule(
                "export const value = 1;",
                as: "host:value",
                documentation: .init(summary: "Invalid\0documentation."),
                typeScriptDeclarations: .init("export const value: number;")
            )
        }

        try await runtime.registerModule(
            "export const value = 2;",
            as: "host:value",
            documentation: "Valid module documentation.",
            typeScriptDeclarations: .init("export const value: number;")
        )
        let module = try await runtime.importModule("host:value")
        let value: Int = try await module.value(forExport: "value", as: Int.self)
        #expect(value == 2)
    }

    @Test("documented assignments are restricted to the runtime global object")
    func documentedAssignmentsRequireGlobalObject() async throws {
        let runtime = try JavaScriptRuntime()
        let raw = try await runtime.evaluate("({})")
        let object = try #require(raw.objectValue)

        await #expect(throws: JavaScriptError.self) {
            try await object.set(
                42,
                forProperty: "answer",
                documentation: "The answer."
            )
        }
        #expect(try await object.hasProperty("answer") == false)
    }

    @Test("globals objects and Swift modules share the same schema metadata")
    func exportsShareSchemaMetadata() async throws {
        actor Directory {
            func user(id: Int) -> User { User(id: id, name: "Ada") }
        }

        let runtime = try JavaScriptRuntime()
        let directory = Directory()
        try await runtime.global.set(User(id: 1, name: "Grace"), forProperty: "currentUser")
        try await runtime.export(directory, as: "directory") { directory, export in
            export.function("user", options: .init(parameterNames: ["id"])) { id in
                await directory.user(id: id)
            }
            export.value("1.0", as: "version", documentation: "Directory API version.")
        }
        try await runtime.defineModule("host:users") { module in
            module.value(User(id: 2, name: "Lin"), as: "featured")
        }

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()

        #expect(declarations.contains("declare let currentUser: QuickJSKit.User;"))
        #expect(declarations.contains("declare const directory: {"))
        #expect(declarations.contains("user: (id: number | bigint) => Promise<QuickJSKit.User>;"))
        #expect(declarations.contains("readonly version: string;"))
        #expect(declarations.contains("declare module \"host:users\""))
        #expect(declarations.contains("export const featured: QuickJSKit.User;"))
    }

    @Test("source modules carry explicit companion declarations")
    func sourceModulesCarryCompanionDeclarations() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.registerModule(
            "export const answer = 42;",
            as: "host:answer",
            typeScriptDeclarations: .init("export const answer: number;")
        )

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()

        #expect(declarations.contains("""
        declare module "host:answer" {
            export const answer: number;
        }
        """))
    }

    @Test("strict generation identifies missing schemas and permissive generation is explicit")
    func completenessIsExplicit() async throws {
        struct RuntimeOnlyModel: Codable, Sendable { let value: Int }

        let runtime = try JavaScriptRuntime()
        try await runtime.global.set(
            RuntimeOnlyModel(value: 42),
            forProperty: "runtimeOnly"
        )
        let environment = try await runtime.environmentDescription()

        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptDeclarations()
        }
        let permissive = try environment.typeScriptDeclarations(
            options: .init(completeness: .allowUntyped)
        )
        #expect(permissive.contains("declare let runtimeOnly: unknown;"))
    }

    @Test("snapshots preserve replacement and stale-removal semantics")
    func snapshotsTrackBindingOwnership() async throws {
        let runtime = try JavaScriptRuntime()
        let stale = try await runtime.function("value") { () -> Int in 1 }
        try await runtime.global.set("replacement", forProperty: "value")
        _ = try await stale.remove()

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains("declare let value: string;"))

        try await runtime.global.deleteProperty("value")
        let afterDeletion = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(!afterDeletion.contains("declare let value"))
        #expect(!afterDeletion.contains("declare function value"))
    }

    @Test("workspace artifacts are deterministic and safe to regenerate")
    func workspaceIsManaged() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function("answer") { () -> Int in 42 }
        let environment = try await runtime.environmentDescription()
        let workspace = try environment.typeScriptWorkspace(
            options: .init(
                sourceGlobs: ["Scripts/**/*.js", "Scripts/**/*.ts"],
                checkJavaScript: true,
                includePackageJSON: true
            )
        )

        #expect(workspace.files.map(\.path) == [
            "package.json",
            "quickjskit.generated.d.ts",
            "quickjskit.generated.d.ts.map",
            "tsconfig.json",
        ])
        #expect(workspace.files.first { $0.path == "tsconfig.json" }?.contents.contains(
            "\"checkJs\": true"
        ) == true)

        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        try workspace.write(to: directory)
        try workspace.write(to: directory)

        let declarationURL = directory.appendingPathComponent("quickjskit.generated.d.ts")
        try "user edit".write(to: declarationURL, atomically: true, encoding: .utf8)
        #expect(throws: TypeScriptToolingError.self) {
            try workspace.write(to: directory)
        }
        try workspace.write(to: directory, policy: .overwriteGenerated)
        #expect(try String(contentsOf: declarationURL, encoding: .utf8).contains(
            "declare function answer"
        ))
    }

    @Test("conflicting named definitions fail deterministically")
    func conflictingDefinitionsFail() async throws {
        let first = TypeScriptSchema.interface(
            "Conflict",
            properties: [.init("value", type: .string)]
        )
        let second = TypeScriptSchema.interface(
            "Conflict",
            properties: [.init("value", type: .number)]
        )
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription(
            including: [first, second]
        )

        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptDeclarations()
        }
    }

    @Test("invalid and unknown declaration scopes fail deterministically")
    func invalidScopesFailDeterministically() async throws {
        let invalidNamespace = TypeScriptSchema.interface(
            "Value",
            scope: .namespace("Acme..Models"),
            properties: []
        )
        let unknownModule = TypeScriptSchema.interface(
            "Value",
            scope: .module("missing"),
            properties: []
        )
        let runtime = try JavaScriptRuntime()

        do {
            _ = try await runtime.environmentDescription(including: [invalidNamespace])
                .typeScriptDeclarations()
            Issue.record("Generation unexpectedly accepted an invalid namespace.")
        } catch let error as TypeScriptToolingError {
            #expect(error.message.contains("Acme..Models"))
        }

        do {
            _ = try await runtime.environmentDescription(including: [unknownModule])
                .typeScriptDeclarations()
            Issue.record("Generation unexpectedly accepted an unknown module scope.")
        } catch let error as TypeScriptToolingError {
            #expect(error.message.contains("unknown module 'missing'"))
        }
    }

    @Test("missing cross-scope references identify their destination")
    func missingCrossScopeReferencesIdentifyTheirDestination() async throws {
        let schema = TypeScriptSchema(
            type: .named("Missing", scope: .module("host:users")),
            definitions: [],
            scope: .global
        )
        let runtime = try JavaScriptRuntime()
        try await runtime.defineModule("host:users") { _ in }

        do {
            _ = try await runtime.environmentDescription(including: [schema])
                .typeScriptDeclarations()
            Issue.record("Generation unexpectedly accepted a missing module type.")
        } catch let error as TypeScriptToolingError {
            #expect(error.message.contains("module 'host:users'.Missing"))
        }
    }

    @Test("definition overrides support explicit cross-scope references")
    func definitionOverridesSupportCrossScopeReferences() async throws {
        let schema = TypeScriptSchema(
            type: .named("Container"),
            definitions: [
                .interface(
                    name: "Container",
                    properties: [
                        .init(
                            "value",
                            type: .named("Shared", scope: "Shared.Models")
                        ),
                    ]
                ),
                .alias(
                    name: "Shared",
                    scope: "Shared.Models",
                    type: .string
                ),
            ],
            scope: "Feature.Models"
        )
        let runtime = try JavaScriptRuntime()
        let declarations = try await runtime.environmentDescription(including: [schema])
            .typeScriptDeclarations()

        #expect(declarations.contains("value: Shared.Models.Shared;"))
        #expect(declarations.contains("type Shared = string;"))
    }

    @Test("global references reject lexical shadowing")
    func globalReferencesRejectShadowing() async throws {
        let schema = TypeScriptSchema(
            type: .named("Container"),
            definitions: [
                .alias(name: "Value", scope: .global, type: .string),
                .alias(name: "Value", type: .number),
                .interface(
                    name: "Container",
                    properties: [
                        .init("value", type: .named("Value", scope: .global)),
                    ]
                ),
            ],
            scope: "Feature"
        )
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription(including: [schema])

        do {
            _ = try environment.typeScriptDeclarations()
            Issue.record("Generation unexpectedly accepted a shadowed global reference.")
        } catch let error as TypeScriptToolingError {
            #expect(error.message.contains("Global TypeScript reference 'Value' is shadowed"))
        }
    }

    @Test("schemas support aliases recursive interfaces optional properties and literal unions")
    func schemasSupportRelatedDefinitions() async throws {
        let schema = TypeScriptSchema(
            type: .named("Node"),
            definitions: [
                .interface(
                    name: "Node",
                    documentation: "A recursive node.",
                    properties: [
                        .init("name", type: .string),
                        .init(
                            "next",
                            type: .union([.named("Node"), .null]),
                            isOptional: true
                        ),
                        .init("state", type: .named("NodeState")),
                    ]
                ),
                .enumeration(
                    name: "NodeState",
                    documentation: "The node state.",
                    cases: [
                        .init(
                            "ready",
                            value: .string("ready"),
                            documentation: "The node is ready."
                        ),
                        .init("count", value: .integer(1)),
                    ]
                ),
                .alias(
                    name: "NodeList",
                    documentation: "A collection of nodes.",
                    type: .array(.named("Node"))
                ),
            ]
        )
        let runtime = try JavaScriptRuntime()
        let declarations = try await runtime.environmentDescription(including: [schema])
            .typeScriptDeclarations()

        #expect(declarations.contains("interface Node"))
        #expect(declarations.contains("next?: Node | null;"))
        #expect(declarations.contains("type NodeList = Node[];"))
        #expect(declarations.contains("type NodeState = \"ready\" | 1;"))
        #expect(declarations.contains("The node is ready."))
    }

    @Test("known source modules require declarations in strict mode")
    func sourceModuleCompletenessIsExplicit() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.registerModule("export const value = 1;", as: "untyped")
        let environment = try await runtime.environmentDescription()

        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptDeclarations()
        }
        let declarations = try environment.typeScriptDeclarations(
            options: .init(completeness: .allowUntyped)
        )
        #expect(declarations.contains("declare module \"untyped\";"))
    }

    @Test("source modules owning schemas require companion declarations")
    func sourceModuleSchemasRequireCompanions() async throws {
        let schema = TypeScriptSchema.interface(
            "Value",
            scope: .module("untyped"),
            properties: [.init("value", type: .number)]
        )
        let runtime = try JavaScriptRuntime()
        try await runtime.registerModule("export const value = 1;", as: "untyped")
        let environment = try await runtime.environmentDescription(including: [schema])

        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptDeclarations(
                options: .init(completeness: .allowUntyped)
            )
        }
    }

    @Test("canonical Swift representations map to exact TypeScript types")
    func canonicalMappingsAreExact() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "representations",
            options: .init(
                parameterNames: [
                    "flag", "text", "small", "wide", "bytes", "date",
                    "url", "big", "items", "lookup",
                ]
            )
        ) { (
            _: Bool,
            _: String,
            _: Int32,
            _: Int64,
            _: Data,
            _: Date,
            _: URL,
            _: JavaScriptBigInt,
            _: [String?],
            _: [String: UInt32]
        ) -> [Int64?] in
            []
        }
        try await runtime.function(
            "optionalPlacement",
            options: .init(parameterNames: ["maybe", "required", "tail"])
        ) { (_: String?, _: String, _: Int?) -> Void in }

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains("flag: boolean"))
        #expect(declarations.contains("text: string"))
        #expect(declarations.contains("small: number"))
        #expect(declarations.contains("wide: number | bigint"))
        #expect(declarations.contains("bytes: Uint8Array"))
        #expect(declarations.contains("date: Date"))
        #expect(declarations.contains("url: string"))
        #expect(declarations.contains("big: bigint"))
        #expect(declarations.contains("items: (string | null)[]"))
        #expect(declarations.contains("lookup: Record<string, number>"))
        #expect(declarations.contains("): (number | bigint | null)[];"))
        #expect(declarations.contains(
            "optionalPlacement(maybe: string | null | undefined, required: string, tail?: number | bigint | null): void;"
        ))
    }

    @Test("snapshots are detached and independent runtimes render identically")
    func snapshotsAreDetachedAndDeterministic() async throws {
        var firstRuntime: JavaScriptRuntime? = try JavaScriptRuntime()
        let secondRuntime = try JavaScriptRuntime()
        weak let releasedRuntime = firstRuntime

        try await firstRuntime?.global.set("one", forProperty: "alpha")
        try await firstRuntime?.global.set(2, forProperty: "beta")
        try await firstRuntime?.defineModule("ordered") { module in
            module.value(2, as: "beta")
            module.value("one", as: "alpha")
        }
        try await secondRuntime.global.set(2, forProperty: "beta")
        try await secondRuntime.global.set("one", forProperty: "alpha")
        try await secondRuntime.defineModule("ordered") { module in
            module.value("one", as: "alpha")
            module.value(2, as: "beta")
        }

        let first = try await firstRuntime?.environmentDescription()
        let second = try await secondRuntime.environmentDescription()
        firstRuntime = nil
        await Task.yield()

        #expect(releasedRuntime == nil)
        #expect(try #require(first).typeScriptDeclarations() == second.typeScriptDeclarations())
    }

    @Test("workspace regeneration removes only unchanged obsolete files")
    func workspaceRemovesOnlyOwnedObsoleteFiles() async throws {
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription()
        let withPackage = try environment.typeScriptWorkspace(
            options: .init(includePackageJSON: true)
        )
        let withoutPackage = try environment.typeScriptWorkspace()
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        try withPackage.write(to: directory)
        let unrelated = directory.appendingPathComponent("notes.txt")
        try "keep".write(to: unrelated, atomically: true, encoding: .utf8)
        try withoutPackage.write(to: directory)
        #expect(!FileManager.default.fileExists(
            atPath: directory.appendingPathComponent("package.json").path
        ))
        #expect(FileManager.default.fileExists(atPath: unrelated.path))

        try withPackage.write(to: directory)
        let package = directory.appendingPathComponent("package.json")
        try "modified".write(to: package, atomically: true, encoding: .utf8)
        try withoutPackage.write(to: directory)
        #expect(try String(contentsOf: package, encoding: .utf8) == "modified")
    }

    @Test("workspace inputs and managed symlinks are rejected")
    func workspaceRejectsUnsafePaths() async throws {
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription()
        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptWorkspace(
                options: .init(sourceGlobs: ["../Scripts/**/*.ts"])
            )
        }

        let workspace = try environment.typeScriptWorkspace()
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let external = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
        defer {
            try? FileManager.default.removeItem(at: directory)
            try? FileManager.default.removeItem(at: external)
        }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try "external".write(to: external, atomically: true, encoding: .utf8)
        try FileManager.default.createSymbolicLink(
            at: directory.appendingPathComponent("quickjskit.generated.d.ts"),
            withDestinationURL: external
        )
        #expect(throws: TypeScriptToolingError.self) {
            try workspace.write(to: directory)
        }
    }
}
