import Foundation
import QuickJSKit
import Testing

@Suite("TypeScript tooling examples")
struct TypeScriptToolingExamplesTests {
    struct User: Codable, Sendable, Equatable, TypeScriptSchemaProviding {
        let id: Int
        let name: String

        static let typeScriptSchema = TypeScriptSchema.interface(
            "User",
            documentation: "A user visible to embedded scripts.",
            properties: [
                .init("id", type: .number, isReadonly: true),
                .init("name", type: .string, isReadonly: true),
            ]
        )
    }

    @Test("a runtime snapshot renders typed globals deterministically")
    func snapshotRendersTypedGlobals() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "loadUser",
            options: .init(
                parameterNames: ["id", "nickname"],
                documentation: "Loads a user."
            )
        ) { (_: Int64, _: String?) async throws -> User? in
            User(id: 42, name: "Ada")
        }

        let environment = try await runtime.environmentDescription()
        let declarations = try environment.typeScriptDeclarations()

        #expect(declarations == """
        // Generated by QuickJSKit. Do not edit.

        declare namespace QuickJSKit {
            /** A user visible to embedded scripts. */
            interface User {
                readonly id: number;
                readonly name: string;
            }
        }

        /**
         * Loads a user.
         * @throws When the Swift operation fails.
         */
        declare function loadUser(id: number | bigint, nickname?: string | null): Promise<QuickJSKit.User | null>;
        """ + "\n")
    }

    @Test("globals objects and Swift modules share the same schema metadata")
    func exportsShareSchemaMetadata() async throws {
        actor Directory {
            func user(id: Int) -> User { User(id: id, name: "Ada") }
        }

        let runtime = try JavaScriptRuntime()
        let directory = Directory()
        try await runtime.global.set(User(id: 1, name: "Grace"), forProperty: "currentUser")
        try await runtime.export(directory, as: "directory") { directory, export in
            export.function("user", options: .init(parameterNames: ["id"])) { id in
                await directory.user(id: id)
            }
            export.value("1.0", as: "version", documentation: "Directory API version.")
        }
        try await runtime.defineModule("host:users") { module in
            module.value(User(id: 2, name: "Lin"), as: "featured")
        }

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()

        #expect(declarations.contains("declare let currentUser: QuickJSKit.User;"))
        #expect(declarations.contains("declare const directory: {"))
        #expect(declarations.contains("user: (id: number | bigint) => Promise<QuickJSKit.User>;"))
        #expect(declarations.contains("readonly version: string;"))
        #expect(declarations.contains("declare module \"host:users\""))
        #expect(declarations.contains("export const featured: QuickJSKit.User;"))
    }

    @Test("source modules carry explicit companion declarations")
    func sourceModulesCarryCompanionDeclarations() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.registerModule(
            "export const answer = 42;",
            as: "host:answer",
            typeScriptDeclarations: .init("export const answer: number;")
        )

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()

        #expect(declarations.contains("""
        declare module "host:answer" {
            export const answer: number;
        }
        """))
    }

    @Test("strict generation identifies missing schemas and permissive generation is explicit")
    func completenessIsExplicit() async throws {
        struct RuntimeOnlyModel: Codable, Sendable { let value: Int }

        let runtime = try JavaScriptRuntime()
        try await runtime.global.set(
            RuntimeOnlyModel(value: 42),
            forProperty: "runtimeOnly"
        )
        let environment = try await runtime.environmentDescription()

        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptDeclarations()
        }
        let permissive = try environment.typeScriptDeclarations(
            options: .init(completeness: .allowUntyped)
        )
        #expect(permissive.contains("declare let runtimeOnly: unknown;"))
    }

    @Test("snapshots preserve replacement and stale-removal semantics")
    func snapshotsTrackBindingOwnership() async throws {
        let runtime = try JavaScriptRuntime()
        let stale = try await runtime.function("value") { () -> Int in 1 }
        try await runtime.global.set("replacement", forProperty: "value")
        _ = try await stale.remove()

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains("declare let value: string;"))

        try await runtime.global.deleteProperty("value")
        let afterDeletion = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(!afterDeletion.contains("declare let value"))
        #expect(!afterDeletion.contains("declare function value"))
    }

    @Test("workspace artifacts are deterministic and safe to regenerate")
    func workspaceIsManaged() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function("answer") { () -> Int in 42 }
        let environment = try await runtime.environmentDescription()
        let workspace = try environment.typeScriptWorkspace(
            options: .init(
                sourceGlobs: ["Scripts/**/*.js", "Scripts/**/*.ts"],
                checkJavaScript: true,
                includePackageJSON: true
            )
        )

        #expect(workspace.files.map(\.path) == [
            "package.json",
            "quickjskit.generated.d.ts",
            "tsconfig.json",
        ])
        #expect(workspace.files.first { $0.path == "tsconfig.json" }?.contents.contains(
            "\"checkJs\": true"
        ) == true)

        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        try workspace.write(to: directory)
        try workspace.write(to: directory)

        let declarationURL = directory.appendingPathComponent("quickjskit.generated.d.ts")
        try "user edit".write(to: declarationURL, atomically: true, encoding: .utf8)
        #expect(throws: TypeScriptToolingError.self) {
            try workspace.write(to: directory)
        }
        try workspace.write(to: directory, policy: .overwriteGenerated)
        #expect(try String(contentsOf: declarationURL, encoding: .utf8).contains(
            "declare function answer"
        ))
    }

    @Test("conflicting named definitions fail deterministically")
    func conflictingDefinitionsFail() async throws {
        let first = TypeScriptSchema.interface(
            "Conflict",
            properties: [.init("value", type: .string)]
        )
        let second = TypeScriptSchema.interface(
            "Conflict",
            properties: [.init("value", type: .number)]
        )
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription(
            including: [first, second]
        )

        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptDeclarations()
        }
    }

    @Test("schemas support aliases recursive interfaces optional properties and literal unions")
    func schemasSupportRelatedDefinitions() async throws {
        let schema = TypeScriptSchema(
            type: .named("Node"),
            definitions: [
                .interface(
                    name: "Node",
                    documentation: "A recursive node.",
                    properties: [
                        .init("name", type: .string),
                        .init(
                            "next",
                            type: .union([.named("Node"), .null]),
                            isOptional: true
                        ),
                        .init("state", type: .named("NodeState")),
                    ]
                ),
                .enumeration(
                    name: "NodeState",
                    documentation: "The node state.",
                    cases: [
                        .init(
                            "ready",
                            value: .string("ready"),
                            documentation: "The node is ready."
                        ),
                        .init("count", value: .integer(1)),
                    ]
                ),
                .alias(
                    name: "NodeList",
                    documentation: "A collection of nodes.",
                    type: .array(.named("Node"))
                ),
            ]
        )
        let runtime = try JavaScriptRuntime()
        let declarations = try await runtime.environmentDescription(including: [schema])
            .typeScriptDeclarations()

        #expect(declarations.contains("interface Node"))
        #expect(declarations.contains("next?: Node | null;"))
        #expect(declarations.contains("type NodeList = Node[];"))
        #expect(declarations.contains("type NodeState = \"ready\" | 1;"))
        #expect(declarations.contains("The node is ready."))
    }

    @Test("known source modules require declarations in strict mode")
    func sourceModuleCompletenessIsExplicit() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.registerModule("export const value = 1;", as: "untyped")
        let environment = try await runtime.environmentDescription()

        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptDeclarations()
        }
        let declarations = try environment.typeScriptDeclarations(
            options: .init(completeness: .allowUntyped)
        )
        #expect(declarations.contains("declare module \"untyped\";"))
    }

    @Test("canonical Swift representations map to exact TypeScript types")
    func canonicalMappingsAreExact() async throws {
        let runtime = try JavaScriptRuntime()
        try await runtime.function(
            "representations",
            options: .init(
                parameterNames: [
                    "flag", "text", "small", "wide", "bytes", "date",
                    "url", "big", "items", "lookup",
                ]
            )
        ) { (
            _: Bool,
            _: String,
            _: Int32,
            _: Int64,
            _: Data,
            _: Date,
            _: URL,
            _: JavaScriptBigInt,
            _: [String?],
            _: [String: UInt32]
        ) -> [Int64?] in
            []
        }
        try await runtime.function(
            "optionalPlacement",
            options: .init(parameterNames: ["maybe", "required", "tail"])
        ) { (_: String?, _: String, _: Int?) -> Void in }

        let declarations = try await runtime.environmentDescription()
            .typeScriptDeclarations()
        #expect(declarations.contains("flag: boolean"))
        #expect(declarations.contains("text: string"))
        #expect(declarations.contains("small: number"))
        #expect(declarations.contains("wide: number | bigint"))
        #expect(declarations.contains("bytes: Uint8Array"))
        #expect(declarations.contains("date: Date"))
        #expect(declarations.contains("url: string"))
        #expect(declarations.contains("big: bigint"))
        #expect(declarations.contains("items: (string | null)[]"))
        #expect(declarations.contains("lookup: Record<string, number>"))
        #expect(declarations.contains("): (number | bigint | null)[];"))
        #expect(declarations.contains(
            "optionalPlacement(maybe: string | null | undefined, required: string, tail?: number | bigint | null): void;"
        ))
    }

    @Test("snapshots are detached and independent runtimes render identically")
    func snapshotsAreDetachedAndDeterministic() async throws {
        var firstRuntime: JavaScriptRuntime? = try JavaScriptRuntime()
        let secondRuntime = try JavaScriptRuntime()
        weak let releasedRuntime = firstRuntime

        try await firstRuntime?.global.set("one", forProperty: "alpha")
        try await firstRuntime?.global.set(2, forProperty: "beta")
        try await firstRuntime?.defineModule("ordered") { module in
            module.value(2, as: "beta")
            module.value("one", as: "alpha")
        }
        try await secondRuntime.global.set(2, forProperty: "beta")
        try await secondRuntime.global.set("one", forProperty: "alpha")
        try await secondRuntime.defineModule("ordered") { module in
            module.value("one", as: "alpha")
            module.value(2, as: "beta")
        }

        let first = try await firstRuntime?.environmentDescription()
        let second = try await secondRuntime.environmentDescription()
        firstRuntime = nil
        await Task.yield()

        #expect(releasedRuntime == nil)
        #expect(try #require(first).typeScriptDeclarations() == second.typeScriptDeclarations())
    }

    @Test("workspace regeneration removes only unchanged obsolete files")
    func workspaceRemovesOnlyOwnedObsoleteFiles() async throws {
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription()
        let withPackage = try environment.typeScriptWorkspace(
            options: .init(includePackageJSON: true)
        )
        let withoutPackage = try environment.typeScriptWorkspace()
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        try withPackage.write(to: directory)
        let unrelated = directory.appendingPathComponent("notes.txt")
        try "keep".write(to: unrelated, atomically: true, encoding: .utf8)
        try withoutPackage.write(to: directory)
        #expect(!FileManager.default.fileExists(
            atPath: directory.appendingPathComponent("package.json").path
        ))
        #expect(FileManager.default.fileExists(atPath: unrelated.path))

        try withPackage.write(to: directory)
        let package = directory.appendingPathComponent("package.json")
        try "modified".write(to: package, atomically: true, encoding: .utf8)
        try withoutPackage.write(to: directory)
        #expect(try String(contentsOf: package, encoding: .utf8) == "modified")
    }

    @Test("workspace inputs and managed symlinks are rejected")
    func workspaceRejectsUnsafePaths() async throws {
        let runtime = try JavaScriptRuntime()
        let environment = try await runtime.environmentDescription()
        #expect(throws: TypeScriptToolingError.self) {
            try environment.typeScriptWorkspace(
                options: .init(sourceGlobs: ["../Scripts/**/*.ts"])
            )
        }

        let workspace = try environment.typeScriptWorkspace()
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        let external = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
        defer {
            try? FileManager.default.removeItem(at: directory)
            try? FileManager.default.removeItem(at: external)
        }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try "external".write(to: external, atomically: true, encoding: .utf8)
        try FileManager.default.createSymbolicLink(
            at: directory.appendingPathComponent("quickjskit.generated.d.ts"),
            withDestinationURL: external
        )
        #expect(throws: TypeScriptToolingError.self) {
            try workspace.write(to: directory)
        }
    }
}
