internal struct TypeScriptRenderer {
    internal let environment: JavaScriptEnvironmentDescription
    internal let options: TypeScriptDeclarationOptions

    private var allowsUntyped: Bool { options.completeness == .allowUntyped }

    internal func render() throws -> String {
        let resolved = try TypeScriptSchemaResolver(
            environment: environment,
            options: options
        ).resolve()
        let documentation = TypeScriptTSDocRenderer(
            completeness: options.documentationCompleteness
        )
        var sections = ["// Generated by QuickJSKit. Do not edit."]

        let globalDefinitions = resolved.definitions(in: .global)
        if !globalDefinitions.isEmpty {
            sections.append(
                try globalDefinitions.map {
                    try renderDefinition($0, documentation: documentation)
                }.joined(separator: "\n\n")
            )
        }

        let namespaceScopes = Set(resolved.definitions.compactMap { definition in
            if case .namespace = definition.key.scope { definition.key.scope } else { nil }
        }).sorted()
        for scope in namespaceScopes {
            guard case let .namespace(components) = scope else { continue }
            let body = try resolved.definitions(in: scope).map {
                try renderDefinition($0, documentation: documentation)
            }.joined(separator: "\n\n")
            sections.append(
                "declare namespace \(components.joined(separator: ".")) {\n\(indent(body))\n}"
            )
        }

        if !environment.globals.isEmpty {
            sections.append(
                try environment.globals.map {
                    try renderGlobal(
                        $0,
                        resolved: resolved,
                        documentation: documentation
                    )
                }.joined(separator: "\n\n")
            )
        }
        if !environment.modules.isEmpty {
            sections.append(
                try environment.modules.map {
                    try renderModule(
                        $0,
                        definitions: resolved.definitions(in: .module($0.specifier)),
                        resolved: resolved,
                        documentation: documentation
                    )
                }.joined(separator: "\n\n")
            )
        }
        return sections.joined(separator: "\n\n") + "\n"
    }

    private func renderDefinition(
        _ definition: ResolvedTypeScriptDefinition,
        documentation: TypeScriptTSDocRenderer
    ) throws -> String {
        let prefix: String
        if case .module = definition.key.scope { prefix = "export " } else { prefix = "" }
        let declaration: String
        switch definition.kind {
        case let .interface(properties):
            let body = try properties.map { property in
                let propertyDocumentation = try documentation.propertyDocumentation(
                    property,
                    definition: definition
                )
                let readonly = property.isReadonly ? "readonly " : ""
                let optional = property.isOptional ? "?" : ""
                let line = "\(readonly)\(propertyKey(property.name))\(optional): "
                    + "\(try render(property.type, from: definition.key.scope));"
                return [propertyDocumentation, line].compactMap { $0 }.joined(separator: "\n")
            }.joined(separator: "\n")
            declaration = "\(prefix)interface \(definition.key.name) {\n\(indent(body))\n}"
        case let .alias(type):
            declaration = "\(prefix)type \(definition.key.name) = "
                + "\(try render(type, from: definition.key.scope));"
        case let .enumeration(cases):
            declaration = "\(prefix)type \(definition.key.name) = "
                + cases.map { renderTypeScriptLiteral($0.value) }.joined(separator: " | ")
                + ";"
        }
        return [try documentation.definitionDocumentation(definition), declaration]
            .compactMap { $0 }.joined(separator: "\n")
    }

    private func renderGlobal(
        _ global: EnvironmentGlobalDescription,
        resolved: ResolvedTypeScriptEnvironment,
        documentation: TypeScriptTSDocRenderer
    ) throws -> String {
        guard TypeScriptIdentifier.isValid(global.name) else {
            throw TypeScriptToolingError(
                "Global name '\(global.name)' cannot be represented as a TypeScript declaration."
            )
        }
        switch global {
        case let .function(function):
            return try renderFunction(
                function,
                prefix: "declare function",
                suffix: ";",
                from: .global,
                resolved: resolved,
                documentation: documentation,
                documentationLocation: "global function '\(function.name)'"
            )
        case let .value(value):
            let declarationDocumentation = try documentation.documentation(
                value.documentation,
                at: "global value '\(value.name)'"
            )
            let declaration = "declare let \(value.name): "
                + "\(try render(value.type, from: .global, resolved: resolved));"
            return [declarationDocumentation, declaration].compactMap { $0 }.joined(separator: "\n")
        case let .type(type):
            return try renderRuntimeType(
                type,
                prefix: "declare const",
                scope: .global,
                resolved: resolved,
                documentation: documentation
            )
        case let .object(name, objectDocumentation, members):
            let declarationDocumentation = try documentation.documentation(
                objectDocumentation,
                at: "exported object '\(name)'"
            )
            let body = try members.map {
                try renderObjectMember(
                    $0,
                    objectName: name,
                    resolved: resolved,
                    documentation: documentation
                )
            }.joined(separator: "\n")
            let declaration = "declare const \(name): {\n\(indent(body))\n};"
            return [declarationDocumentation, declaration].compactMap { $0 }.joined(separator: "\n")
        }
    }

    private func renderObjectMember(
        _ member: EnvironmentMemberDescription,
        objectName: String,
        resolved: ResolvedTypeScriptEnvironment,
        documentation: TypeScriptTSDocRenderer
    ) throws -> String {
        switch member {
        case let .function(function):
            return try renderFunction(
                function,
                prefix: "readonly \(propertyKey(function.name))",
                suffix: ";",
                asProperty: true,
                from: .global,
                resolved: resolved,
                documentation: documentation,
                documentationLocation: "exported method '\(objectName).\(function.name)'"
            )
        case .type:
            throw TypeScriptToolingError(
                "JavaScript types cannot be rendered inside object exports."
            )
        case let .value(value):
            let declarationDocumentation = try documentation.documentation(
                value.documentation,
                at: "exported value '\(objectName).\(value.name)'"
            )
            let readonly = value.isReadOnly ? "readonly " : ""
            let declaration = "\(readonly)\(propertyKey(value.name)): "
                + "\(try render(value.type, from: .global, resolved: resolved));"
            return [declarationDocumentation, declaration].compactMap { $0 }.joined(separator: "\n")
        }
    }

    private func renderModule(
        _ module: EnvironmentModuleDescription,
        definitions: [ResolvedTypeScriptDefinition],
        resolved: ResolvedTypeScriptEnvironment,
        documentation: TypeScriptTSDocRenderer
    ) throws -> String {
        let specifier = module.specifier
        let moduleDocumentation: TypeScriptDocumentation?
        var bodySections = try definitions.map {
            try renderDefinition($0, documentation: documentation)
        }

        switch module {
        case let .source(_, sourceDocumentation, declarations):
            moduleDocumentation = sourceDocumentation
            if let declarations {
                bodySections.append(declarations.body)
            } else if !definitions.isEmpty {
                throw TypeScriptToolingError(
                    "Source module '\(specifier)' requires companion TypeScript declarations "
                        + "when it owns generated schema definitions."
                )
            } else if !allowsUntyped {
                throw TypeScriptToolingError(
                    "Source module '\(specifier)' has no companion TypeScript declarations."
                )
            } else if bodySections.isEmpty {
                let renderedDocumentation = try documentation.documentation(
                    sourceDocumentation,
                    at: "source module '\(specifier)'"
                )
                let declaration = "declare module \(quotedJSONString(specifier));"
                return [renderedDocumentation, declaration].compactMap { $0 }
                    .joined(separator: "\n")
            }
        case let .swift(_, swiftDocumentation, members):
            moduleDocumentation = swiftDocumentation
            bodySections.append(
                contentsOf: try members.map {
                    try renderModuleMember(
                        $0,
                        specifier: specifier,
                        resolved: resolved,
                        documentation: documentation
                    )
                }
            )
        }

        let renderedDocumentation = try documentation.documentation(
            moduleDocumentation,
            at: "\(module.isSwift ? "Swift" : "source") module '\(specifier)'"
        )
        let body = bodySections.joined(separator: "\n\n")
        let declaration = "declare module \(quotedJSONString(specifier)) {\n\(indent(body))\n}"
        return [renderedDocumentation, declaration].compactMap { $0 }.joined(separator: "\n")
    }

    private func renderModuleMember(
        _ member: EnvironmentMemberDescription,
        specifier: String,
        resolved: ResolvedTypeScriptEnvironment,
        documentation: TypeScriptTSDocRenderer
    ) throws -> String {
        guard member.name == "default" || TypeScriptIdentifier.isValid(member.name) else {
            throw TypeScriptToolingError(
                "Module export name '\(member.name)' cannot be represented as a TypeScript declaration."
            )
        }
        let scope = ResolvedTypeScriptScope.module(specifier)
        switch member {
        case let .function(function) where function.name == "default":
            let type = try functionType(function, from: scope, resolved: resolved)
            let declaration = "const defaultExport: \(type);\nexport default defaultExport;"
            return [
                try documentation.functionDocumentation(
                    function,
                    at: "default function export of module '\(specifier)'"
                ),
                declaration,
            ].compactMap { $0 }.joined(separator: "\n")
        case let .function(function):
            return try renderFunction(
                function,
                prefix: "export function",
                suffix: ";",
                from: scope,
                resolved: resolved,
                documentation: documentation,
                documentationLocation: "function export '\(function.name)' of module '\(specifier)'"
            )
        case let .type(type):
            return try renderRuntimeType(
                type,
                prefix: "export const",
                scope: scope,
                resolved: resolved,
                documentation: documentation
            )
        case let .value(value) where value.name == "default":
            let declarationDocumentation = try documentation.documentation(
                value.documentation,
                at: "default value export of module '\(specifier)'"
            )
            let declaration = "const defaultExport: "
                + "\(try render(value.type, from: scope, resolved: resolved));\n"
                + "export default defaultExport;"
            return [declarationDocumentation, declaration].compactMap { $0 }.joined(separator: "\n")
        case let .value(value):
            let declarationDocumentation = try documentation.documentation(
                value.documentation,
                at: "value export '\(value.name)' of module '\(specifier)'"
            )
            let declaration = "export const \(value.name): "
                + "\(try render(value.type, from: scope, resolved: resolved));"
            return [declarationDocumentation, declaration].compactMap { $0 }.joined(separator: "\n")
        }
    }

    private func renderRuntimeType(
        _ type: EnvironmentTypeDescription,
        prefix: String,
        scope: ResolvedTypeScriptScope,
        resolved: ResolvedTypeScriptEnvironment,
        documentation: TypeScriptTSDocRenderer
    ) throws -> String {
        let renderedDocumentation = try documentation.documentation(
            type.documentation,
            at: "JavaScript type '\(type.name)'"
        )
        let declaration: String
        switch type.kind {
        case .structure:
            declaration = "\(prefix) \(type.name): {\n"
                + "    new(value: \(type.name)): \(type.name);\n"
                + "};"
        case let .enumeration(cases):
            let properties = cases.map { enumCase in
                "    readonly \(propertyKey(enumCase.name)): "
                    + "\(renderTypeScriptLiteral(enumCase.value));"
            }.joined(separator: "\n")
            declaration = "\(prefix) \(type.name): {\n"
                + "    (value: \(type.name)): \(type.name);\n"
                + properties + "\n};"
        case let .host(constructors, staticMembers, instanceMembers):
            let classPrefix = prefix.hasPrefix("export") ? "export class" : "declare class"
            var members: [String] = []
            for constructor in constructors {
                let parameters = try renderParameters(
                    constructor.parameters,
                    from: scope,
                    resolved: resolved
                )
                let docs = try documentation.functionDocumentation(
                    constructor,
                    at: "constructor of JavaScript host type '\(type.name)'"
                )
                let signature = constructor.effects.isAsync
                    ? "static create(\(parameters)): Promise<\(type.name)>;"
                    : "constructor(\(parameters));"
                members.append(
                    [docs, signature]
                        .compactMap { $0 }
                        .joined(separator: "\n")
                )
            }
            for member in staticMembers {
                members.append(
                    try renderHostMember(
                        member,
                        prefix: "static ",
                        scope: scope,
                        resolved: resolved,
                        documentation: documentation,
                        owner: type.name
                    )
                )
            }
            for member in instanceMembers {
                members.append(
                    try renderHostMember(
                        member,
                        prefix: "",
                        scope: scope,
                        resolved: resolved,
                        documentation: documentation,
                        owner: type.name
                    )
                )
            }
            declaration = "\(classPrefix) \(type.name) {\n"
                + indent(members.joined(separator: "\n\n"))
                + "\n}"
        }
        return [renderedDocumentation, declaration].compactMap { $0 }
            .joined(separator: "\n")
    }

    private func renderHostMember(
        _ member: EnvironmentMemberDescription,
        prefix: String,
        scope: ResolvedTypeScriptScope,
        resolved: ResolvedTypeScriptEnvironment,
        documentation: TypeScriptTSDocRenderer,
        owner: String
    ) throws -> String {
        switch member {
        case let .function(function):
            let parameters = try renderParameters(
                function.parameters,
                from: scope,
                resolved: resolved
            )
            let result = try renderFunctionResult(
                function,
                from: scope,
                resolved: resolved
            )
            let docs = try documentation.functionDocumentation(
                function,
                at: "member '\(function.name)' of host type '\(owner)'"
            )
            let declaration = "\(prefix)\(propertyKey(function.name))"
                + "(\(parameters)): \(result);"
            return [docs, declaration].compactMap { $0 }.joined(separator: "\n")
        case let .value(value):
            let docs = try documentation.documentation(
                value.documentation,
                at: "property '\(value.name)' of host type '\(owner)'"
            )
            let readonly = value.isReadOnly ? "readonly " : ""
            let declaration = "\(prefix)\(readonly)\(propertyKey(value.name)): "
                + "\(try render(value.type, from: scope, resolved: resolved));"
            return [docs, declaration].compactMap { $0 }.joined(separator: "\n")
        case .type:
            throw TypeScriptToolingError(
                "A JavaScript host type cannot contain another runtime type."
            )
        }
    }

    private func renderFunction(
        _ function: EnvironmentFunctionDescription,
        prefix: String,
        suffix: String,
        asProperty: Bool = false,
        from scope: ResolvedTypeScriptScope,
        resolved: ResolvedTypeScriptEnvironment,
        documentation: TypeScriptTSDocRenderer,
        documentationLocation: String
    ) throws -> String {
        let parameters = try renderParameters(function.parameters, from: scope, resolved: resolved)
        let result = try renderFunctionResult(function, from: scope, resolved: resolved)
        let declaration = asProperty
            ? "\(prefix): (\(parameters)) => \(result)\(suffix)"
            : "\(prefix) \(function.name)(\(parameters)): \(result)\(suffix)"
        return [
            try documentation.functionDocumentation(function, at: documentationLocation),
            declaration,
        ].compactMap { $0 }.joined(separator: "\n")
    }

    private func functionType(
        _ function: EnvironmentFunctionDescription,
        from scope: ResolvedTypeScriptScope,
        resolved: ResolvedTypeScriptEnvironment
    ) throws -> String {
        "(\(try renderParameters(function.parameters, from: scope, resolved: resolved))) => "
            + "\(try renderFunctionResult(function, from: scope, resolved: resolved))"
    }

    private func renderParameters(
        _ parameters: [BindingParameterDescription],
        from scope: ResolvedTypeScriptScope,
        resolved: ResolvedTypeScriptEnvironment
    ) throws -> String {
        var firstTrailingOptional = parameters.count
        for index in parameters.indices.reversed() {
            guard parameters[index].type.isOptional else { break }
            firstTrailingOptional = index
        }
        return try parameters.enumerated().map { index, parameter in
            let trailing = index >= firstTrailingOptional && parameter.type.isOptional
            let marker = trailing ? "?" : ""
            let position: TypePosition = trailing ? .optionalParameter : .parameter
            return "\(parameter.name)\(marker): "
                + "\(try render(parameter.type, position: position, from: scope, resolved: resolved))"
        }.joined(separator: ", ")
    }

    private func renderFunctionResult(
        _ function: EnvironmentFunctionDescription,
        from scope: ResolvedTypeScriptScope,
        resolved: ResolvedTypeScriptEnvironment
    ) throws -> String {
        let result = try render(function.result, from: scope, resolved: resolved)
        return function.effects.isAsync ? "Promise<\(result)>" : result
    }

    private enum TypePosition { case parameter, optionalParameter, result }

    private func render(
        _ shape: BindingTypeShape,
        position: TypePosition = .result,
        from scope: ResolvedTypeScriptScope,
        resolved: ResolvedTypeScriptEnvironment
    ) throws -> String {
        switch shape {
        case .void: return "void"
        case .unknown: return "unknown"
        case .null: return "null"
        case .undefined: return "undefined"
        case .boolean: return "boolean"
        case .string, .url: return "string"
        case .bigInt: return "bigint"
        case .floatingPoint: return "number"
        case let .integer(_, _, bits): return bits <= 32 ? "number" : "number | bigint"
        case let .array(element):
            let element = try render(element, from: scope, resolved: resolved)
            return needsArrayParentheses(element) ? "(\(element))[]" : "\(element)[]"
        case let .dictionary(value):
            return "Record<string, \(try render(value, from: scope, resolved: resolved))>"
        case .data: return "Uint8Array"
        case .date: return "Date"
        case let .optional(wrapped):
            let base = try render(wrapped, position: position, from: scope, resolved: resolved)
            switch position {
            case .result, .optionalParameter: return "\(base) | null"
            case .parameter: return "\(base) | null | undefined"
            }
        case let .codable(_, schema?):
            guard let type = resolved.schemaTypes[schema] else {
                throw TypeScriptToolingError("A collected TypeScript schema could not be resolved.")
            }
            return try render(type, from: scope)
        case let .codable(swiftName, nil):
            guard allowsUntyped else {
                throw TypeScriptToolingError(
                    "Swift type '\(swiftName)' does not provide a TypeScript schema."
                )
            }
            return "unknown"
        case let .host(name, declaredScope):
            let hostScope: TypeScriptDeclarationScope?
            if let declaredScope {
                hostScope = declaredScope
            } else {
                hostScope = try inferredHostTypeScope(named: name, from: scope)
            }
            guard let hostScope else { return name }
            return renderHostReference(name, scope: hostScope, from: scope)
        }
    }

    private func inferredHostTypeScope(
        named name: String,
        from currentScope: ResolvedTypeScriptScope
    ) throws -> TypeScriptDeclarationScope? {
        var scopes: [TypeScriptDeclarationScope] = []
        for global in environment.globals {
            guard case let .type(type) = global,
                  type.name == name,
                  case .host = type.kind else { continue }
            scopes.append(.global)
        }
        for module in environment.modules {
            guard case let .swift(specifier, _, members) = module else { continue }
            for member in members {
                guard case let .type(type) = member,
                      type.name == name,
                      case .host = type.kind else { continue }
                scopes.append(.module(specifier))
            }
        }
        if case let .module(currentSpecifier) = currentScope,
           scopes.contains(.module(currentSpecifier)) {
            return .module(currentSpecifier)
        }
        let unique = Array(Set(scopes))
        guard unique.count <= 1 else {
            throw TypeScriptToolingError(
                "JavaScript host type '\(name)' has multiple runtime locations; give its macro an explicit declaration scope."
            )
        }
        return unique.first
    }

    private func renderHostReference(
        _ name: String,
        scope hostScope: TypeScriptDeclarationScope,
        from currentScope: ResolvedTypeScriptScope
    ) -> String {
        switch hostScope {
        case .global:
            return name
        case let .namespace(path):
            return "\(path).\(name)"
        case let .module(specifier):
            if case let .module(current) = currentScope, current == specifier {
                return name
            }
            return "import(\(quotedJSONString(specifier))).\(name)"
        }
    }

    private func render(
        _ type: ResolvedTypeScriptType,
        from scope: ResolvedTypeScriptScope
    ) throws -> String {
        switch type {
        case .boolean: return "boolean"
        case .string: return "string"
        case .number: return "number"
        case .bigint: return "bigint"
        case .null: return "null"
        case .undefined: return "undefined"
        case .unknown: return "unknown"
        case .date: return "Date"
        case .uint8Array: return "Uint8Array"
        case let .named(key):
            if key.scope == scope { return key.name }
            switch key.scope {
            case .global:
                return key.name
            case let .namespace(components):
                return (components + [key.name]).joined(separator: ".")
            case let .module(specifier):
                return "import(\(quotedJSONString(specifier))).\(key.name)"
            }
        case let .array(element):
            let element = try render(element, from: scope)
            return needsArrayParentheses(element) ? "(\(element))[]" : "\(element)[]"
        case let .record(value):
            return "Record<string, \(try render(value, from: scope))>"
        case let .union(types):
            var rendered: [String] = []
            for type in types {
                let item = try render(type, from: scope)
                if !rendered.contains(item) { rendered.append(item) }
            }
            return rendered.joined(separator: " | ")
        case let .literal(literal):
            return renderTypeScriptLiteral(literal)
        }
    }

    private func propertyKey(_ value: String) -> String {
        TypeScriptIdentifier.isValid(value) ? value : quotedJSONString(value)
    }

    private func needsArrayParentheses(_ value: String) -> Bool {
        value.contains(" | ") || value.contains(" & ")
    }
}

internal func renderTypeScriptLiteral(_ literal: TypeScriptLiteral) -> String {
    switch literal {
    case let .string(value): return quotedJSONString(value)
    case let .integer(value):
        let limit = Int64(JavaScriptValue.maximumSafeInteger)
        return value < -limit || value > limit
            ? "\(value)n"
            : String(value)
    }
}

internal func quotedJSONString(_ value: String) -> String {
    var result = "\""
    for scalar in value.unicodeScalars {
        switch scalar.value {
        case 0x22: result += "\\\""
        case 0x5C: result += "\\\\"
        case 0x08: result += "\\b"
        case 0x0C: result += "\\f"
        case 0x0A: result += "\\n"
        case 0x0D: result += "\\r"
        case 0x09: result += "\\t"
        case 0..<0x20:
            let hex = String(scalar.value, radix: 16, uppercase: true)
            result += "\\u" + String(repeating: "0", count: 4 - hex.count) + hex
        default: result.unicodeScalars.append(scalar)
        }
    }
    return result + "\""
}

private func indent(_ value: String) -> String {
    value.split(separator: "\n", omittingEmptySubsequences: false)
        .map { $0.isEmpty ? "" : "    \($0)" }
        .joined(separator: "\n")
}

private extension BindingTypeShape {
    var isOptional: Bool {
        if case .optional = self { true } else { false }
    }
}

private extension EnvironmentModuleDescription {
    var isSwift: Bool {
        if case .swift = self { true } else { false }
    }
}
