internal import Foundation

internal struct TypeScriptRenderer {
    internal let environment: JavaScriptEnvironmentDescription
    internal let options: TypeScriptDeclarationOptions

    private var allowsUntyped: Bool { options.completeness == .allowUntyped }

    internal func render() throws -> String {
        guard Self.isIdentifier(options.typeNamespace) else {
            throw TypeScriptToolingError(
                "The TypeScript namespace '\(options.typeNamespace)' is not a valid identifier."
            )
        }

        let definitions = try collectedDefinitions()
        var sections: [String] = [
            "// Generated by QuickJSKit. Do not edit.",
        ]
        if !definitions.isEmpty {
            let body = try definitions.map(renderDefinition).joined(separator: "\n\n")
            sections.append("declare namespace \(options.typeNamespace) {\n\(indent(body))\n}")
        }
        if !environment.globals.isEmpty {
            sections.append(
                try environment.globals.map(renderGlobal).joined(separator: "\n\n")
            )
        }
        if !environment.modules.isEmpty {
            sections.append(
                try environment.modules.map(renderModule).joined(separator: "\n\n")
            )
        }
        return sections.joined(separator: "\n\n") + "\n"
    }

    private func collectedDefinitions() throws -> [TypeScriptDefinition] {
        var schemas = environment.additionalSchemas
        for global in environment.globals { collectSchemas(from: global, into: &schemas) }
        for module in environment.modules { collectSchemas(from: module, into: &schemas) }

        var definitions: [String: TypeScriptDefinition] = [:]
        for schema in schemas {
            for definition in schema.definitions {
                let name = definition.name
                guard Self.isIdentifier(name) else {
                    throw TypeScriptToolingError(
                        "The TypeScript definition name '\(name)' is not a valid identifier."
                    )
                }
                if let existing = definitions[name], existing != definition {
                    throw TypeScriptToolingError(
                        "Conflicting TypeScript definitions use the name '\(name)'."
                    )
                }
                try validate(definition)
                definitions[name] = definition
            }
        }
        let availableNames = Set(definitions.keys)
        var referencedNames: Set<String> = []
        for schema in schemas {
            collectNamedReferences(from: schema.type, into: &referencedNames)
        }
        for definition in definitions.values {
            collectNamedReferences(from: definition, into: &referencedNames)
        }
        if let missing = referencedNames.subtracting(availableNames).sorted().first {
            throw TypeScriptToolingError(
                "TypeScript schema reference '\(missing)' has no matching definition."
            )
        }
        return definitions.values.sorted { $0.name < $1.name }
    }

    private func collectNamedReferences(
        from definition: TypeScriptDefinition,
        into names: inout Set<String>
    ) {
        switch definition {
        case let .interface(_, _, properties):
            for property in properties {
                collectNamedReferences(from: property.type, into: &names)
            }
        case let .alias(_, _, type):
            collectNamedReferences(from: type, into: &names)
        case .enumeration:
            break
        }
    }

    private func collectNamedReferences(
        from type: TypeScriptType,
        into names: inout Set<String>
    ) {
        switch type {
        case let .named(name):
            names.insert(name)
        case let .array(element), let .record(element):
            collectNamedReferences(from: element, into: &names)
        case let .union(types):
            for type in types { collectNamedReferences(from: type, into: &names) }
        default:
            break
        }
    }

    private func collectSchemas(
        from global: EnvironmentGlobalDescription,
        into schemas: inout [TypeScriptSchema]
    ) {
        switch global {
        case let .function(function): collectSchemas(from: function, into: &schemas)
        case let .object(_, members):
            for member in members { collectSchemas(from: member, into: &schemas) }
        case let .value(value): collectSchemas(from: value.type, into: &schemas)
        }
    }

    private func collectSchemas(
        from module: EnvironmentModuleDescription,
        into schemas: inout [TypeScriptSchema]
    ) {
        guard case let .swift(_, members) = module else { return }
        for member in members { collectSchemas(from: member, into: &schemas) }
    }

    private func collectSchemas(
        from member: EnvironmentMemberDescription,
        into schemas: inout [TypeScriptSchema]
    ) {
        switch member {
        case let .function(function): collectSchemas(from: function, into: &schemas)
        case let .value(value): collectSchemas(from: value.type, into: &schemas)
        }
    }

    private func collectSchemas(
        from function: EnvironmentFunctionDescription,
        into schemas: inout [TypeScriptSchema]
    ) {
        for parameter in function.parameters {
            collectSchemas(from: parameter.type, into: &schemas)
        }
        collectSchemas(from: function.result, into: &schemas)
    }

    private func collectSchemas(
        from shape: BindingTypeShape,
        into schemas: inout [TypeScriptSchema]
    ) {
        switch shape {
        case let .optional(wrapped), let .array(wrapped), let .dictionary(wrapped):
            collectSchemas(from: wrapped, into: &schemas)
        case let .codable(_, schema?):
            schemas.append(schema)
        default:
            break
        }
    }

    private func validate(_ definition: TypeScriptDefinition) throws {
        switch definition {
        case let .interface(_, _, properties):
            var names: Set<String> = []
            for property in properties {
                guard names.insert(property.name).inserted else {
                    throw TypeScriptToolingError(
                        "The TypeScript interface '\(definition.name)' contains duplicate property '\(property.name)'."
                    )
                }
            }
        case .alias:
            break
        case let .enumeration(_, _, cases):
            guard !cases.isEmpty else {
                throw TypeScriptToolingError(
                    "The TypeScript literal union '\(definition.name)' must contain at least one case."
                )
            }
            let values = cases.map(\.value)
            guard Set(values).count == values.count else {
                throw TypeScriptToolingError(
                    "The TypeScript literal union '\(definition.name)' contains duplicate values."
                )
            }
        }
    }

    private func renderDefinition(_ definition: TypeScriptDefinition) throws -> String {
        let documentation: String?
        if case let .enumeration(_, baseDocumentation, cases) = definition {
            let documentedCases = cases.compactMap { enumCase -> String? in
                guard let caseDocumentation = enumCase.documentation else { return nil }
                return "- \(enumCase.name) (\(render(enumCase.value))): \(caseDocumentation)"
            }
            documentation = jsDoc(
                ([baseDocumentation].compactMap { $0 } + documentedCases)
                    .joined(separator: "\n")
            )
        } else {
            documentation = jsDoc(definition.documentation)
        }
        let declaration: String
        switch definition {
        case let .interface(name, _, properties):
            let body = try properties.map { property in
                let documentation = jsDoc(property.documentation)
                let readonly = property.isReadonly ? "readonly " : ""
                let optional = property.isOptional ? "?" : ""
                let line = "\(readonly)\(propertyKey(property.name))\(optional): \(try render(property.type, qualified: false));"
                return [documentation, line].compactMap { $0 }.joined(separator: "\n")
            }.joined(separator: "\n")
            declaration = "interface \(name) {\n\(indent(body))\n}"
        case let .alias(name, _, type):
            declaration = "type \(name) = \(try render(type, qualified: false));"
        case let .enumeration(name, _, cases):
            declaration = "type \(name) = " + cases.map { render($0.value) }.joined(separator: " | ") + ";"
        }
        return [documentation, declaration].compactMap { $0 }.joined(separator: "\n")
    }

    private func renderGlobal(_ global: EnvironmentGlobalDescription) throws -> String {
        guard Self.isIdentifier(global.name) else {
            throw TypeScriptToolingError(
                "Global name '\(global.name)' cannot be represented as a TypeScript declaration."
            )
        }
        switch global {
        case let .function(function):
            return try renderFunction(function, prefix: "declare function", suffix: ";")
        case let .value(value):
            let declaration = "declare let \(value.name): \(try render(value.type, position: .result));"
            return [jsDoc(value.documentation), declaration].compactMap { $0 }.joined(separator: "\n")
        case let .object(name, members):
            let body = try members.map(renderObjectMember).joined(separator: "\n")
            return "declare const \(name): {\n\(indent(body))\n};"
        }
    }

    private func renderObjectMember(_ member: EnvironmentMemberDescription) throws -> String {
        switch member {
        case let .function(function):
            return try renderFunction(
                function,
                prefix: "readonly \(propertyKey(function.name))",
                suffix: ";",
                asProperty: true
            )
        case let .value(value):
            let declaration = "readonly \(propertyKey(value.name)): \(try render(value.type, position: .result));"
            return [jsDoc(value.documentation), declaration].compactMap { $0 }.joined(separator: "\n")
        }
    }

    private func renderModule(_ module: EnvironmentModuleDescription) throws -> String {
        switch module {
        case let .source(specifier, declarations?):
            return "declare module \(quotedJSONString(specifier)) {\n\(indent(declarations.body))\n}"
        case let .source(specifier, nil):
            guard allowsUntyped else {
                throw TypeScriptToolingError(
                    "Source module '\(specifier)' has no companion TypeScript declarations."
                )
            }
            return "declare module \(quotedJSONString(specifier));"
        case let .swift(specifier, members):
            let body = try members.map(renderModuleMember).joined(separator: "\n\n")
            return "declare module \(quotedJSONString(specifier)) {\n\(indent(body))\n}"
        }
    }

    private func renderModuleMember(_ member: EnvironmentMemberDescription) throws -> String {
        guard member.name == "default" || Self.isIdentifier(member.name) else {
            throw TypeScriptToolingError(
                "Module export name '\(member.name)' cannot be represented as a TypeScript declaration."
            )
        }
        switch member {
        case let .function(function) where function.name == "default":
            let type = try functionType(function)
            let declaration = "const defaultExport: \(type);\nexport default defaultExport;"
            return [jsDoc(function.documentation, throws: function.effects.isThrowing), declaration]
                .compactMap { $0 }.joined(separator: "\n")
        case let .function(function):
            return try renderFunction(function, prefix: "export function", suffix: ";")
        case let .value(value) where value.name == "default":
            let declaration = "const defaultExport: \(try render(value.type, position: .result));\nexport default defaultExport;"
            return [jsDoc(value.documentation), declaration].compactMap { $0 }.joined(separator: "\n")
        case let .value(value):
            let declaration = "export const \(value.name): \(try render(value.type, position: .result));"
            return [jsDoc(value.documentation), declaration].compactMap { $0 }.joined(separator: "\n")
        }
    }

    private func renderFunction(
        _ function: EnvironmentFunctionDescription,
        prefix: String,
        suffix: String,
        asProperty: Bool = false
    ) throws -> String {
        let parameters = try renderParameters(function.parameters)
        let result = try renderFunctionResult(function)
        let declaration: String
        if asProperty {
            declaration = "\(prefix): (\(parameters)) => \(result)\(suffix)"
        } else {
            declaration = "\(prefix) \(function.name)(\(parameters)): \(result)\(suffix)"
        }
        return [jsDoc(function.documentation, throws: function.effects.isThrowing), declaration]
            .compactMap { $0 }.joined(separator: "\n")
    }

    private func functionType(_ function: EnvironmentFunctionDescription) throws -> String {
        "(\(try renderParameters(function.parameters))) => \(try renderFunctionResult(function))"
    }

    private func renderParameters(_ parameters: [BindingParameterDescription]) throws -> String {
        var firstTrailingOptional = parameters.count
        for index in parameters.indices.reversed() {
            guard parameters[index].type.isOptional else { break }
            firstTrailingOptional = index
        }
        return try parameters.enumerated().map { index, parameter in
            let trailing = index >= firstTrailingOptional && parameter.type.isOptional
            let marker = trailing ? "?" : ""
            return "\(parameter.name)\(marker): \(try render(parameter.type, position: trailing ? .optionalParameter : .parameter))"
        }.joined(separator: ", ")
    }

    private func renderFunctionResult(_ function: EnvironmentFunctionDescription) throws -> String {
        let result = try render(function.result, position: .result)
        return function.effects.isAsync ? "Promise<\(result)>" : result
    }

    private enum TypePosition { case parameter, optionalParameter, result }

    private func render(
        _ shape: BindingTypeShape,
        position: TypePosition = .result
    ) throws -> String {
        switch shape {
        case .void: return "void"
        case .unknown: return "unknown"
        case .null: return "null"
        case .undefined: return "undefined"
        case .boolean: return "boolean"
        case .string, .url: return "string"
        case .bigInt: return "bigint"
        case .floatingPoint: return "number"
        case let .integer(_, _, bits): return bits <= 32 ? "number" : "number | bigint"
        case let .array(element):
            let element = try render(element, position: .result)
            return needsArrayParentheses(element) ? "(\(element))[]" : "\(element)[]"
        case let .dictionary(value):
            return "Record<string, \(try render(value, position: .result))>"
        case .data: return "Uint8Array"
        case .date: return "Date"
        case let .optional(wrapped):
            let base = try render(wrapped, position: position)
            switch position {
            case .result, .optionalParameter: return "\(base) | null"
            case .parameter: return "\(base) | null | undefined"
            }
        case let .codable(_, schema?):
            return try render(schema.type, qualified: true)
        case let .codable(swiftName, nil):
            guard allowsUntyped else {
                throw TypeScriptToolingError(
                    "Swift type '\(swiftName)' does not provide a TypeScript schema."
                )
            }
            return "unknown"
        }
    }

    private func render(_ type: TypeScriptType, qualified: Bool) throws -> String {
        switch type {
        case .boolean: return "boolean"
        case .string: return "string"
        case .number: return "number"
        case .bigint: return "bigint"
        case .null: return "null"
        case .undefined: return "undefined"
        case .unknown: return "unknown"
        case .date: return "Date"
        case .uint8Array: return "Uint8Array"
        case let .named(name):
            guard Self.isIdentifier(name) else {
                throw TypeScriptToolingError("The TypeScript reference '\(name)' is not valid.")
            }
            return qualified ? "\(options.typeNamespace).\(name)" : name
        case let .array(element):
            let element = try render(element, qualified: qualified)
            return needsArrayParentheses(element) ? "(\(element))[]" : "\(element)[]"
        case let .record(value): return "Record<string, \(try render(value, qualified: qualified))>"
        case let .union(types):
            guard !types.isEmpty else {
                throw TypeScriptToolingError("A TypeScript union must contain at least one type.")
            }
            var rendered: [String] = []
            for type in types {
                let item = try render(type, qualified: qualified)
                if !rendered.contains(item) { rendered.append(item) }
            }
            return rendered.joined(separator: " | ")
        case let .literal(literal): return render(literal)
        }
    }

    private func render(_ literal: TypeScriptLiteral) -> String {
        switch literal {
        case let .string(value): quotedJSONString(value)
        case let .integer(value): String(value)
        }
    }

    private func jsDoc(_ documentation: String?, throws: Bool = false) -> String? {
        var lines = documentation?
            .replacingOccurrences(of: "*/", with: "*\\/")
            .split(whereSeparator: { $0.isNewline })
            .map(String.init) ?? []
        if `throws` { lines.append("@throws When the Swift operation fails.") }
        guard !lines.isEmpty else { return nil }
        if lines.count == 1 { return "/** \(lines[0]) */" }
        return (["/**"] + lines.map { " * \($0)" } + [" */"]).joined(separator: "\n")
    }

    private func propertyKey(_ value: String) -> String {
        Self.isIdentifier(value) ? value : quotedJSONString(value)
    }

    private func indent(_ value: String) -> String {
        value.split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "    \($0)" }
            .joined(separator: "\n")
    }

    private func needsArrayParentheses(_ value: String) -> Bool {
        value.contains(" | ") || value.contains(" & ")
    }

    private static func isIdentifier(_ value: String) -> Bool {
        guard let first = value.unicodeScalars.first,
              first == "_" || first == "$" || CharacterSet.letters.contains(first) else {
            return false
        }
        let validScalars = value.unicodeScalars.dropFirst().allSatisfy {
            $0 == "_" || $0 == "$" || CharacterSet.alphanumerics.contains($0)
        }
        return validScalars && !reservedIdentifiers.contains(value)
    }

    private static let reservedIdentifiers: Set<String> = [
        "await", "break", "case", "catch", "class", "const", "continue",
        "debugger", "default", "delete", "do", "else", "enum", "export",
        "extends", "false", "finally", "for", "function", "if", "import",
        "in", "instanceof", "let", "new", "null", "return", "static",
        "super", "switch", "this", "throw", "true", "try", "typeof",
        "var", "void", "while", "with", "yield", "implements", "interface",
        "package", "private", "protected", "public",
    ]
}

internal func quotedJSONString(_ value: String) -> String {
    var result = "\""
    for scalar in value.unicodeScalars {
        switch scalar.value {
        case 0x22: result += "\\\""
        case 0x5C: result += "\\\\"
        case 0x08: result += "\\b"
        case 0x0C: result += "\\f"
        case 0x0A: result += "\\n"
        case 0x0D: result += "\\r"
        case 0x09: result += "\\t"
        case 0..<0x20:
            let hex = String(scalar.value, radix: 16, uppercase: true)
            result += "\\u" + String(repeating: "0", count: 4 - hex.count) + hex
        default: result.unicodeScalars.append(scalar)
        }
    }
    return result + "\""
}

private extension BindingTypeShape {
    var isOptional: Bool {
        if case .optional = self { true } else { false }
    }
}

private extension TypeScriptDefinition {
    var name: String {
        switch self {
        case let .interface(name, _, _), let .alias(name, _, _), let .enumeration(name, _, _):
            name
        }
    }

    var documentation: String? {
        switch self {
        case let .interface(_, documentation, _),
             let .alias(_, documentation, _),
             let .enumeration(_, documentation, _):
            documentation
        }
    }
}
