/// A logical Swift source location attached to generated TypeScript metadata.
public struct TypeScriptSourceLocation: Sendable, Hashable {
    /// The compiler-provided logical file identifier.
    public let fileID: String

    /// The one-based source line.
    public let line: Int

    /// The one-based UTF-8 source column reported by the Swift parser.
    public let column: Int

    /// Creates a logical source location.
    public init(fileID: String, line: Int, column: Int) {
        self.fileID = fileID
        self.line = line
        self.column = column
    }
}

/// Supplies a detached export definition synthesized by `@JavaScriptExport`.
public protocol JavaScriptExportProviding: AnyObject, SendableMetatype {
    /// Structured documentation for the exported object container.
    static var javaScriptExportDocumentation: TypeScriptDocumentation? { get }

    /// The logical Swift declaration location, when generated by a macro.
    static var javaScriptExportSourceLocation: TypeScriptSourceLocation? { get }

    /// The reusable root-aware binding definition.
    static var javaScriptExportDefinition:
        JavaScriptRuntimeTemplate.InstanceExport<Self> { get }
}
